from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_wtf import CSRFProtect
import os 
from flask_talisman import Talisman
import logging
from logging.handlers import RotatingFileHandler
from config import DevelopmentConfig, ProductionConfig

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "main.login"
csrf = CSRFProtect()
talisman = Talisman()

@login_manager.user_loader
def load_user(user_id): # Generated By Copilot
    from .models import User
    try:
        return User.query.get(int(user_id))
    except Exception:
        return None
    
csp = {
    "default-src": ["'self'"],
    "script-src": ["'self'", 'https://cdn.jsdelivr.net'],
    "style-src": ["'self'", 'https://cdn.jsdelivr.net'],
    "img-src": ["'self'", 'data:'],
    "frame-src": ["'none'"],
    "frame-ancestors": ["'none'"],
    "connect-src": ["'self'"],
    "font-src": ["'self'", 'https://fonts.gstatic.com'],
}


def create_app(config_class=DevelopmentConfig):
    app = Flask(__name__)

    # Configure root/basic logging only if no handlers are present.
    if not logging.getLogger().handlers:
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s %(levelname)s [%(name)s] %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )

    # Load configuration: prefer explicit FLASK_CONFIG env override, otherwise use
    # the provided config_class (default: DevelopmentConfig).
    flask_config = os.getenv('FLASK_CONFIG')
    if flask_config:
        app.config.from_object(f'config.{flask_config}')
    else:
        app.config.from_object(config_class)

    # Allow SECRET_KEY to be overridden by environment variable after loading config
    if os.environ.get('SECRET_KEY'):
        app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')

    db.init_app(app)

    ENV = os.getenv('FLASK_ENV', 'production')
    is_dev = ENV == 'development'

    talisman.init_app(
        app,
        content_security_policy=csp,
        force_https=not is_dev, # Generated By Copilot
        strict_transport_security=not is_dev, # Generated By Copilot
        strict_transport_security_max_age=0 if is_dev else 31536000, # Generated By Copilot
        strict_transport_security_include_subdomains=not is_dev, # Generated By Copilot
        frame_options='DENY',
        content_type_nosniff=True,
        referrer_policy='strict-origin-when-cross-origin',
        permissions_policy={"geolocation": [], "fullscreen": ["'self'"], "camera": [], "microphone": []},
    )

    csrf.init_app(app)
    login_manager.init_app(app)

    from .routes import main
    app.register_blueprint(main)

    with app.app_context():
        from .models import User
        db.drop_all()
        db.create_all()

        users = [
            {"username": "user1@email.com", "password": "Userpass!23", "role": "user", "bio": "I'm a basic user"},
            {"username": "mod1@email.com", "password": "Modpass!23", "role": "moderator", "bio": "I'm a moderator"},
            {"username": "admin1@email.com", "password": "Adminpass!23", "role": "admin", "bio": "I'm an administrator"}
        ]

        for user in users:
            user = User(username=user["username"], password=user["password"], role=user["role"], bio=user["bio"])
            db.session.add(user)
            db.session.commit()

    try:
        log_path = os.path.join(os.getcwd(), 'app.log')
        # Avoid attaching multiple RotatingFileHandler instances for the same file
        existing = any(
            isinstance(h, RotatingFileHandler) and getattr(h, 'baseFilename', None) == log_path
            for h in app.logger.handlers
        )
        if not existing:
            file_handler = RotatingFileHandler(log_path, maxBytes=1 * 1024 * 1024, backupCount=5)
            file_handler.setLevel(logging.INFO)
            formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
            file_handler.setFormatter(formatter)
            app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.INFO)
        # Do not propagate to the root logger to avoid duplicate logs if basicConfig is present
        app.logger.propagate = False
    except Exception:
        logging.exception('Failed to configure RotatingFileHandler')

    return app