from flask import Flask
from flask_login import LoginManager
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_wtf import CSRFProtect
import sys
import os 
from flask_talisman import Talisman
import logging
from logging.handlers import RotatingFileHandler
import json
from config import DevelopmentConfig, ProductionConfig

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "main.login"
csrf = CSRFProtect()
talisman = Talisman()

@login_manager.user_loader
def load_user(user_id): # Generated By Copilot
    from .models import User
    try:
        return User.query.get(int(user_id))
    except Exception:
        return None
    
csp = {
    "default-src": ["'self'"],
    "script-src": ["'self'", 'https://cdn.jsdelivr.net'],
    "style-src": ["'self'", 'https://cdn.jsdelivr.net'],
    "img-src": ["'self'", 'data:'],
    "frame-src": ["'none'"],
    "frame-ancestors": ["'none'"],
    "connect-src": ["'self'"],
    "font-src": ["'self'", 'https://fonts.gstatic.com'],
}


def create_app(config_class=DevelopmentConfig):
    app = Flask(__name__)

    if not logging.getLogger().handlers:
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S"
        )

    flask_config = os.getenv("FLASK_CONFIG")
    if flask_config:
        app.config.from_object(f"config.{flask_config}")
    else:
        app.config.from_object(config_class)

    if os.environ.get("SECRET_KEY"):
        app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY")

    db.init_app(app)

    ENV = os.getenv("FLASK_ENV", "production")
    is_dev = ENV == "development"

    talisman.init_app(
        app,
        content_security_policy=csp,
        force_https=not is_dev, # Generated By Copilot
        strict_transport_security=not is_dev, # Generated By Copilot
        strict_transport_security_max_age=0 if is_dev else 31536000, # Generated By Copilot
        strict_transport_security_include_subdomains=not is_dev, # Generated By Copilot
        frame_options="DENY",
        referrer_policy="strict-origin-when-cross-origin",
        permissions_policy={"geolocation": [], "fullscreen": ["\'self\'"], "camera": [], "microphone": []},
    )

    csrf.init_app(app)
    login_manager.init_app(app)

    from .routes import main
    app.register_blueprint(main)

    with app.app_context():
        from .models import User
        db.drop_all()
        db.create_all()

        users = [
            {"username": "user1@email.com", "password": "Userpass!23", "role": "user", "bio": "I'm a basic user"},
            {"username": "mod1@email.com", "password": "Modpass!23", "role": "moderator", "bio": "I'm a moderator"},
            {"username": "admin1@email.com", "password": "Adminpass!23", "role": "admin", "bio": "I'm an administrator"}
        ]

        for user in users:
            user = User(username=user["username"], password=user["password"], role=user["role"], bio=user["bio"])
            db.session.add(user)
            db.session.commit()

    try:
        log_path = os.path.join(os.getcwd(), "app.log")
        existing = any(
            isinstance(h, RotatingFileHandler) and getattr(h, "baseFilename", None) == log_path
            for h in app.logger.handlers
        )
        if not existing:
            file_handler = RotatingFileHandler(log_path, maxBytes=1 * 1024 * 1024, backupCount=5)
            file_handler.setLevel(logging.INFO)
            formatter = logging.Formatter("%(asctime)s %(levelname)s: %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
            file_handler.setFormatter(formatter)
            app.logger.addHandler(file_handler)
        if is_dev: # Generated By Copilot
            existing_stream = any(
                isinstance(h, logging.StreamHandler) and getattr(h, "stream", None) in (sys.stdout, sys.stderr)
                for h in app.logger.handlers
            )
            if not existing_stream:
                stream_handler = logging.StreamHandler(sys.stdout)
                stream_handler.setLevel(logging.INFO)
                stream_handler.setFormatter(formatter)
                app.logger.addHandler(stream_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.propagate = False
    except Exception:
        logging.exception("Failed To Configure Rotating File Handler")

    try: # Generated By Copilot
        security_logger = logging.getLogger("security")
        security_log_path = os.path.join(os.getcwd(), "security.log")
        class JSONFormatter(logging.Formatter):
            def format(self, record):
                record_message = record.getMessage()
                payload = {
                    "timestamp": self.formatTime(record, self.datefmt),
                    "level": record.levelname,
                    "logger": record.name,
                    "message": record_message,
                }
                for key in ("event", "user_id", "username", "ip", "path"):
                    val = getattr(record, key, None)
                    if val is not None:
                        payload[key] = val
                try:
                    return json.dumps(payload, ensure_ascii=False)
                except Exception:
                    return super().format(record)

        sec_existing = any(
            isinstance(h, RotatingFileHandler) and getattr(h, "baseFilename", None) == security_log_path
            for h in security_logger.handlers
        )

        if not sec_existing: # Generated By Copilot
            sec_handler = RotatingFileHandler(security_log_path, maxBytes=1 * 1024 * 1024, backupCount=5)
            sec_handler.setLevel(logging.INFO)
            sec_handler.setFormatter(JSONFormatter(datefmt="%Y-%m-%d %H:%M:%S"))
            security_logger.addHandler(sec_handler)

        if is_dev: # Generated By Copilot
            sec_stream_existing = any(isinstance(h, logging.StreamHandler) for h in security_logger.handlers)
            if not sec_stream_existing:
                sec_stream = logging.StreamHandler(sys.stdout)
                sec_stream.setLevel(logging.INFO)
                sec_stream.setFormatter(JSONFormatter(datefmt="%Y-%m-%d %H:%M:%S"))
                security_logger.addHandler(sec_stream)

        security_logger.setLevel(logging.INFO)
        security_logger.propagate = False
    except Exception:
        logging.exception("Failed To Configure Security Logger")

    return app