from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
import re
from flask_login import current_user
from app.models import User

passwordBlacklist = {"Password123$", "Qwerty123!", "Adminadmin1@", "weLcome123!"}

def password_validator(form, field):
    pw = (field.data or "")
    if len(pw) < 10:
        raise ValidationError("Password Must Be At Least 10 Characters Long.")
    if not re.search(r"[A-Z]", pw): # Generated By Copilot
        raise ValidationError("Password Must Contain At Least One Uppercase Letter.")
    if not re.search(r"\d", pw):
        raise ValidationError("Password Must Contain At Least One Digit.")
    if not re.search(r"[^A-Za-z0-9]", pw): # Generated By Copilot
        raise ValidationError("Password Must Contain At Least One Special Character.")
    if re.search(r"(.)\1{2,}", pw): # Generated By Copilot
        raise ValidationError("Password Must Not Contain Repeated Character Sequences.")
    if pw in passwordBlacklist:
        raise ValidationError("This Password Is Not Allowed; Choose A Stronger Password.")

    # Generated By Copilot
    identifiers = []
    for attr in ("username", "email"):
        try:
            val = getattr(form, attr).data
        except Exception:
            val = None
        if val:
            identifiers.append(str(val).lower())
    try:
        if current_user and getattr(current_user, "username", None):
            identifiers.append(str(getattr(current_user, "username")).lower())
    except Exception:
        pass

    for ident in identifiers:
        if ident and ident in pw.lower():
            raise ValidationError("Password Must Not Contain Your Username Or Email.")

class RegistrationForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email(), Length(max=254)])
    password = PasswordField("Password", validators=[DataRequired(), password_validator])
    password2 = PasswordField("Repeat Password", validators=[DataRequired(), EqualTo("password")])
    bio = TextAreaField("Biography", validators=[DataRequired(), Length(max=500)])
    submit = SubmitField("Register")

    def validate_email(self, field):
        existing = User.query.filter_by(username=field.data).first()
        if existing is not None:
            raise ValidationError("Please Use A Different Email Address.")
        
class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Email(), Length(max=254)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=10, max=20)])
    submit = SubmitField("Login")

class ChangePasswordForm(FlaskForm):
    oldPassword = PasswordField("Old Password", validators=[DataRequired()])
    newPassword = PasswordField("New Password", validators=[DataRequired(), password_validator, EqualTo("confirmPassword", message="Passwords Must Match")])
    confirmPassword = PasswordField("Confirm New Password", validators=[DataRequired()])
    submit = SubmitField("Change Password")
    