import traceback
from flask import request, render_template, redirect, url_for, session, Blueprint, flash, abort
from flask_login import current_user, login_user, logout_user, login_required
from flask import current_app
from functools import wraps
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from urllib.parse import urlparse
import bleach
import logging
from werkzeug.security import check_password_hash
from app import db
from datetime import datetime, timedelta, timezone
from app.models import User
import logging
from logging import getLogger
from app.forms import RegistrationForm, LoginForm, ChangePasswordForm

main = Blueprint("main", __name__)
securityLogger = getLogger("security")

def role_required(*roles):
    
    def decorator(f):
        @wraps(f)
        @login_required
        def wrapped(*args, **kwargs):
            if len(roles) == 1 and isinstance(roles[0], (list, tuple, set)): # Generated By Copilot
                allowed = list(roles[0])
            else:
                allowed = list(roles)

            userRole = getattr(current_user, "role", None)
            if userRole not in allowed:
                stack = "".join(traceback.format_stack(limit=25)) # Generated By Copilot
                current_app.logger.warning(
                    "Unauthorized Access Attempt User=%s Role=%s Path=%s", # Generated By Copilot
                    getattr(current_user, "id", None), userRole, request.path
                )
                try:
                    securityLogger.warning("Access Denied", extra={
                        "event": "Access Denied",
                        "user_id": getattr(current_user, "id", None),
                        "username": getattr(current_user, "username", None),
                        "role": userRole,
                        "ip": request.remote_addr,
                        "path": request.path,
                    })
                except Exception:
                    current_app.logger.exception("Failed To Emit Structured Security Log For Access Denied")
                abort(403, description=f"Access denied.\n\n--- STACK (demo) ---\n{stack}")
            return f(*args, **kwargs)
        return wrapped
    return decorator

@main.route("/")
def home():
    return render_template("home.html")

@main.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid Username Or Password", "error")
            current_app.logger.warning("Failed Login For Email=%s From %s", form.username.data, request.remote_addr)
            try:
                securityLogger.warning("Failed Login", extra={
                    "event": "Failed Login",
                    "username": form.username.data,
                    "ip": request.remote_addr,
                    "path": request.path,
                })
            except Exception:
                current_app.logger.exception("Failed To Emit Structured Security Log For Failed Login")
            return redirect(url_for("main.login"))

        session.clear()
        login_user(user)
        current_app.logger.info("Login Success For UserId=%s From %s", user.id, request.remote_addr)
        try:
            securityLogger.info("Login Success", extra={
                "event": "Login Success",
                "user_id": getattr(user, "id", None),
                "username": getattr(user, "username", None),
                "ip": request.remote_addr,
                "path": request.path,
            })
        except Exception:
            current_app.logger.exception("Failed To Emit Structured Security Log For Login Success")
        
        next_page = request.args.get("next")
        if not next_page or urlparse(next_page).netloc != "":
            next_page = url_for("main.home")
        return redirect(next_page)

    return render_template("login.html", title="Sign In", form=form)

@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.login"))

@main.route("/dashboard")
@login_required
def dashboard():
    username = getattr(current_user, "username", None)
    bio = getattr(current_user, "bio", "")
    return render_template("dashboard.html", username=username, bio=bio)

@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        allowedTags = ["b", "i", "u", "em", "strong", "a", "p", "ul", "ol", "li", "br"]
        allowedAttrs = {"a": ["href", "title"]}
        cleanBio = bleach.clean(form.bio.data or "", tags=allowedTags, attributes=allowedAttrs)

        user = User(username=form.email.data, password=form.password.data, role="user", bio=cleanBio)
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            flash("Email Already Exists. Please Choose A Different One.", "error")
            try:
                securityLogger.warning("Duplicate Registration", extra={
                    "event": "Duplicate Registration",
                    "username": form.email.data if getattr(form, "email", None) else None,
                    "ip": request.remote_addr,
                    "path": request.path,
                })
            except Exception:
                current_app.logger.exception("Failed To Emit Structured Security Log For Duplicate Registration")
            return redirect(url_for("main.register"))

        flash("Congratulations, You Are Now A Registered User!", "Success")
        try:
            securityLogger.info("Registration", extra={
                "event": "Registration",
                "username": form.email.data,
                "ip": request.remote_addr,
                "path": request.path,
            })
        except Exception:
            current_app.logger.exception("Failed To Emit Structured Security Log For Registration")
        return redirect(url_for("main.login"))

    return render_template("register.html", form=form)

@main.route("/admin-panel")
@role_required("admin")
def admin():
    return render_template("admin.html")

@main.route("/moderator")
@role_required("moderator", "admin")
def moderator():
    return render_template("moderator.html")

@main.route("/user-dashboard")
@role_required("user", "moderator", "admin")
def user_dashboard():
    return render_template("user_dashboard.html", username=current_user.username)

@main.route("/change-password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        currentPassword = form.oldPassword.data
        newPassword = form.newPassword.data

        if not current_user.check_password(currentPassword): # Generated By Copilot
            try:
                userId = current_user.get_id() if getattr(current_user, "is_authenticated", False) else "anonymous"
                current_app.logger.warning("Failed Password Re-Authentication For User=%s From %s", userId, request.remote_addr)
                try:
                    securityLogger.warning("Failed Reauth", extra={
                        "event": "Failed Reauth",
                        "user_id": userId,
                        "username": getattr(current_user, "username", None),
                        "ip": request.remote_addr,
                        "path": request.path,
                    })
                except Exception:
                    current_app.logger.exception("Failed To Emit Structured Security Log For Failed Reauth")
            except Exception:
                current_app.logger.warning("Failed Password Re-Authentication For Unknown User")
            flash("Unable To Change Password", "error")
            return render_template("change_password.html", form=form)

        if current_user.check_password(newPassword):
            flash("Unable To Change Password", "error")
            return render_template("change_password.html", form=form)

        current_user.set_password(newPassword)
        db.session.commit()

        flash("Password Changed Successfully", "Success")
        current_app.logger.info("Password Changed For UserId=%s From %s", current_user.get_id(), request.remote_addr)
        try:
            securityLogger.info("Password Changed", extra={
                "event": "Password Changed",
                "user_id": current_user.get_id(),
                "username": getattr(current_user, "username", None),
                "ip": request.remote_addr,
                "path": request.path,
            })
        except Exception:
            current_app.logger.exception("Failed To Emit Structured Security Log For Password Changed")
        return redirect(url_for("main.user_dashboard"))

    return render_template("change_password.html", form=form)

@main.before_app_request
def check_idle_timeout():
    now = datetime.now(timezone.utc)
    lastActivity = session.get("last_activity", now) 
    if now - lastActivity > timedelta(minutes=15):
        session.clear()
        return redirect(url_for("main.login"))
    session["last_activity"] = now

@main.errorhandler(400)
def bad_request(error):
    return render_template("400.html", error=error), 400

@main.errorhandler(403)
def forbidden(error):
    return render_template("403.html", error=error), 403

@main.errorhandler(404)
def not_found(error):
    return render_template("404.html", error=error), 404

@main.errorhandler(500)
def internal_error(error):
    db.session.rollback()
    return render_template("500.html", error=error), 500